// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZhB56KPbBofPrBwn9W-RWSP992bNVXo',
    appId: '1:195694526144:web:83314b652b540d327ef725',
    messagingSenderId: '195694526144',
    projectId: 'restrohub-c1d17',
    authDomain: 'restrohub-c1d17.firebaseapp.com',
    storageBucket: 'restrohub-c1d17.firebasestorage.app',
    measurementId: 'G-PBXD0Y16H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANoLhvsGGP64we48SLOwY97aWk3gVHWxM',
    appId: '1:195694526144:android:b6f9d490156f91257ef725',
    messagingSenderId: '195694526144',
    projectId: 'restrohub-c1d17',
    storageBucket: 'restrohub-c1d17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3k-qawfHqsDlfUGnD3Pr-IigpDENQCvI',
    appId: '1:195694526144:ios:118e6b5b4c9b7f8a7ef725',
    messagingSenderId: '195694526144',
    projectId: 'restrohub-c1d17',
    storageBucket: 'restrohub-c1d17.firebasestorage.app',
    androidClientId: '195694526144-c1qvhl45fttaqi2dk48jn4j56borstlp.apps.googleusercontent.com',
    iosClientId: '195694526144-f0mebgr7jf3ljt8ku89e77q815a37jak.apps.googleusercontent.com',
    iosBundleId: 'com.example.restroHub',
  );
}
